### ISSUE TITLE
Will this be ported to IV-SDK .NET or 1.2 at some point?

### ISSUE THREAD

**Issue by SandeMC** [ClonkAndre/ProjectThunderIV#1]
Given the whole thing with people phasing out 1.0.8.0, it would be nice if this was transferred to IV-SDK .NET which would eventually support 1.2 I believe

**Comment by ClonkAndre** [comment]
Transformation done!
IV-SDK .NET CE support can come now!

**Comment by SandeMC** [comment]
Awesome, thank you
