### ISSUE TITLE
ProjectThunderIV not work for the Complete Edition

### ISSUE THREAD

**Issue by CC-Services** [ClonkAndre/ProjectThunderIV#2]
EN: Yes, as the title suggests, as you probably know, ProjectThunderIV cannot be run in the latest version of GTA 4 (Complete Edition), although there is ScriptHookDotNet for the edition. So I ask you to release an update so that you don't have to downgrade. Thanks

DE: Ja, wie der Titel schon lautet ProjectThunderIV kann man wie du sicherlich selbst weißt nicht in der neusten Version von GTA 4 (Complete Edition) ausführen, obwohl es ScriptHookDotNet für die Edition gibt. Also bitte ich dich auch noch ein Update rauszubringe um eben kein downgrade durchführen zu müssen. Danke

**Comment by ClonkAndre** [comment]
Project Thunder was made using the [IV-SDK .NET](https://github.com/ClonkAndre/IV-SDK-DotNet) SDK which, at the moment, is only supported on version 1070/1080 of GTA IV.

IV-SDK .NET will eventually receive support for the latest version in the future.

**Comment by CC-Services** [comment]
@ClonkAndre Funktioniert die Version 1.0 mit dem klassischen ASI Loader?

**Comment by ClonkAndre** [comment]
Not sure what the classic ASI Loader is but i guess so. Every ASI Loader should be able to load it.
Note that the 1.0 is only for version 1040, 1070 and 1080 of GTA IV.

**Comment by CC-Services** [comment]
@ClonkAndre du kannst auch Deutsch schreiben 😉 Gibt es denn keine Möglichkeit das auf der neusten Version auszuführen wäre **Mega** 👍

**Comment by ClonkAndre** [comment]
I prefer writing in english because, this is a public issue, and everyone can read it, so i would like everyone to understand what has been written here 😉

But unfortunately, there is no way to get this mod to work on the newest version of GTA IV at the moment 😭
