### ISSUE TITLE
Range of light sources

### ISSUE THREAD

**Issue by Damierror** [ClonkAndre/ProjectThunderIV#5]
The range of the fire and sirens of special equipment is too low, it is necessary to increase it to 50m horizontally, in the game for some reason it is only large vertically...
I made a hack with fire in the explosionFx file but it looks bad because the light doesn't flicker
![Снимок экрана (17877)](https://github.com/user-attachments/assets/1226492a-f5e2-469c-bfa8-4ba446ac92b2)
![Снимок экрана (17878)](https://github.com/user-attachments/assets/98ca63bd-c93d-422f-9d18-017dce71fc0e)
![Снимок экрана (17886)](https://github.com/user-attachments/assets/ea31434e-3545-4168-a82f-8f6e4b290323)

**Comment by ClonkAndre** [comment]
Not related to Project Thunder. Closing.
